plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - participant_information/**
theme: jekyll-theme-minimal
collections:
  participant_information:
    output: true
    permalink: participant_information/
navigation:
- text: Overview
  internal: true
  url: .
- text: Participant info
  internal: true
  url: /participant_information/
