plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
title: Rabies Accessible Genomic Epidemiology (RAGE) workshop 
logo: /icon/RAGE_train2.jpg
email: kirstyn.brunker@glasgow.ac.uk
color-scheme: auto
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - participant_information/**
  - day5/**
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
collections:
  participant_information:
    output: true
    permalink: participant_information/
  day5:
    output: true
    permalink: day5/
navigation:
  - name: Overview
    link: /
    sublist:
      - name: Programme
        link: /#programme
      - name: Instructors and facilitators
        link: /#instructors-and-facilitators
  - name: Participant info
    link: /participant_information/README.html
  - name: Workshop material
    link: /day5/day5_GLUE_MADDOG.html
