vplugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - participant_information/**
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
collections:
  participant_information:
    output: true
    permalink: participant_information/
navigation:
  - name: Overview
    link: ./README.html
  - name: Participant info
    link: ./participant_information/README.html
  - name: Workshop material
      sublist:
      - name: Day 1
        link: ./Day 1
