vplugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - participant_information/**
  - day5/**
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
collections:
  participant_information:
    output: true
    permalink: participant_information/
navigation:
  - name: Overview
    link: ./README.html
  - name: Participant info
    link: ./participant_information/README.html
