vplugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - participant_information/**
  - day3/**
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
collections:
  participant_information:
    output: true
    permalink: participant_information/
navigation:
  - name: Overview
    link: ./README.html
      sublist:
      - name: Programme
        link: ./#Programme
  - name: Participant info
    link: ./participant_information/README.html
  - name: Workshop material
    link: ./day5/day5_GLUE_MADDOG.html
