plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - participant_information/**
theme: jekyll-theme-minimal
collections:
  participant_information:
    output: true
    permalink: participant_information/
