plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - participant_information/**
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
collections:
  participant_information:
    output: true
    permalink: participant_information/
navigation:
  - name: Readme
    link: ./README.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
  - ...
