plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - participant_information/**
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
collections:
  participant_information:
    output: true
    permalink: participant_information/
navigation:
  - text: Overview
    internal: true
    url: .
  - text: Participant info
    internal: true
    url: https://rage-toolkit.github.io/RAGE-workshop-2024/participant_information/
sidebar:
  - title: "Title"
    image: "/assets/images/your-image.jpg"
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
    nav: ./
